# Generated by Django 4.0.4 on 2022-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POS_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the Goods')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand of the Goods')),
                ('type', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=255)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
